### ISSUE TITLE
Type of the `callback` field in `PromiseWithCallbackArgs`

### ISSUE THREAD

**Issue by mooori** [aurora-is-near/aurora-contracts-sdk#14]
https://github.com/aurora-is-near/aurora-contracts-sdk/blob/221e2dce8da0a8e4e531bc44a1fc97f6a4a33915/docs/NearFromAurora.md?plain=1#L118-L121

Since this is `Near -> Aurora` shouldn't the type of `callback` be `FunctionCallArgsvV2` as mentioned in `AuroraFromNear.md`?

**Comment by birchmd** [comment]
This is `Aurora -> Near`. The callback can be any arbitrary promise, not necessarily a call back to an Aurora function.

**Comment by mooori** [comment]
> This is Aurora -> Near. 

I was referring to the callback of that case, which I assumed to be `Near -> Aurora`. Like for example here:

https://github.com/aurora-is-near/aurora-contracts-sdk/blob/221e2dce8da0a8e4e531bc44a1fc97f6a4a33915/examples/social-db-from-aurora/contract/src/SocialDB.sol#L52-L61

Also this documentation mentions a callback `Near -> Aurora`:

https://github.com/aurora-is-near/aurora-contracts-sdk/blob/221e2dce8da0a8e4e531bc44a1fc97f6a4a33915/docs/NearFromAurora.md?plain=1#L102-L104

So if `PromiseWithCallbackArgs.callback` is `Aurora -> Near` the `PromiseCreateArgs` will be used to create the input to call an EVM contract (`FunctionCallArgsV2`)?

**Comment by birchmd** [comment]
It is possible that the callback is `Near -> Aurora`, but it could be `Near -> Near` (callback is handled by another Near contract) and then `Near -> Aurora`. The point is that a general promise captures all the possible use-cases because Aurora calls are a special case of general Near calls.

**Comment by mooori** [comment]
In case the callback is `Near -> Aurora`, I was wondering how the input for the EVM call is generated from `PromiseCreateArgs`? Because `PromiseCreateArgs` takes a Near account ID and `attached_balance` is in `Yocto` but `FunctionCallArgsV2` requires an EVM `Address` and an attached balance in `WeiU256`.

**Comment by birchmd** [comment]
The promise is a function call to the Aurora contract, and the argument for that call is of type `FunctionCallArgs`. It's true that the args can specify a Wei amount to attach, but this is resolved by the EVM (i.e. Aurora Engine), so no tokens are moved at the Near level. It's a little confusing, but one way to think about it is that the promise is describing an EVM transaction that will happen rather than being the transaction itself.

Any NEAR balance attached to the promise would then be owned by the Aurora account. There is no reason to do this, so the SDK will not attach Near to callbacks targeting Aurora.

**Comment by mooori** [comment]
Thanks for the clarifications. Users would probably just call `near.auroraCall` (as in the example above), which takes care of this.
